# author : ???
# reference : https://zzang9ha.tistory.com/415

# Profile ??
# - dev : ???, ??? ??? db create/create
# - test : ??? ?? ???? ?? ?, db create-drop
# - alpha : ?? ?? ??? ???, db validate
# - prod : ?? ?, db validate

spring:
  profiles:
    active: # dev, test, alpha, prod
      - dev
    include:
      - common-setting